import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { BrandColors, hexToRgb } from '@/types/branding';

interface PDFOptions {
  filename?: string;
  orientation?: 'portrait' | 'landscape';
  format?: 'a4' | 'letter' | 'legal';
  branding?: {
    logoUrl?: string;
    agencyName: string;
    colors: BrandColors;
    headerText?: string;
    footerText?: string;
  };
}

/**
 * Convert hex color to RGB array for jsPDF
 */
function hexToPdfRgb(hex: string): [number, number, number] {
  const rgb = hexToRgb(hex);
  if (!rgb) return [0, 0, 0];
  return [rgb.r, rgb.g, rgb.b];
}

/**
 * Add logo to PDF if available
 */
async function addLogoToPDF(
  pdf: jsPDF, 
  logoUrl: string, 
  x: number, 
  y: number, 
  maxHeight: number = 15
): Promise<number> {
  return new Promise((resolve) => {
    const img = new Image();
    img.crossOrigin = 'anonymous';
    
    img.onload = () => {
      try {
        const aspectRatio = img.width / img.height;
        const height = maxHeight;
        const width = height * aspectRatio;
        
        // Scale down if too wide
        const maxWidth = 50;
        const finalWidth = width > maxWidth ? maxWidth : width;
        const finalHeight = finalWidth / aspectRatio;
        
        pdf.addImage(logoUrl, 'PNG', x, y, finalWidth, finalHeight);
        resolve(finalHeight);
      } catch (error) {
        console.error('Failed to add logo:', error);
        resolve(0);
      }
    };
    
    img.onerror = () => {
      resolve(0);
    };
    
    img.src = logoUrl;
  });
}

export async function exportElementToPDF(
  elementId: string, 
  options: PDFOptions = {}
): Promise<void> {
  const { 
    filename = `report-${new Date().toISOString().split('T')[0]}`, 
    orientation = 'portrait',
    format = 'a4',
    branding
  } = options;

  const element = document.getElementById(elementId);
  if (!element) {
    throw new Error(`Element with id '${elementId}' not found`);
  }

  try {
    // Create canvas from element
    const canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true,
      logging: false,
      backgroundColor: branding?.colors.surface || '#ffffff',
    });

    // Calculate dimensions
    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF({
      orientation,
      unit: 'mm',
      format,
    });

    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = pdf.internal.pageSize.getHeight();
    
    // Add branded header if branding is provided
    let headerHeight = 10;
    if (branding) {
      const primaryColor = hexToPdfRgb(branding.colors.primary);
      
      // Header background
      pdf.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
      pdf.rect(0, 0, pdfWidth, 25, 'F');
      
      // Add logo
      if (branding.logoUrl) {
        const logoHeight = await addLogoToPDF(pdf, branding.logoUrl, 15, 5);
        headerHeight = Math.max(headerHeight, logoHeight + 10);
      }
      
      // Add agency name
      pdf.setFontSize(16);
      pdf.setTextColor(255, 255, 255);
      const textX = branding.logoUrl ? 35 : 15;
      pdf.text(branding.agencyName, textX, 15);
      
      // Add header text if provided
      if (branding.headerText) {
        pdf.setFontSize(9);
        pdf.text(branding.headerText, textX, 20);
      }
      
      headerHeight = 30;
    }

    const imgWidth = canvas.width;
    const imgHeight = canvas.height;
    const ratio = Math.min((pdfWidth - 20) / imgWidth, (pdfHeight - headerHeight - 30) / imgHeight);

    const imgX = (pdfWidth - imgWidth * ratio) / 2;
    let imgY = headerHeight + 5;

    // Add image to PDF
    pdf.addImage(
      imgData, 
      'PNG', 
      imgX, 
      imgY, 
      imgWidth * ratio, 
      imgHeight * ratio
    );

    // Add branded footer
    const pageCount = pdf.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      pdf.setPage(i);
      
      if (branding) {
        const primaryColor = hexToPdfRgb(branding.colors.primary);
        pdf.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
        pdf.rect(0, pdfHeight - 12, pdfWidth, 12, 'F');
        
        pdf.setFontSize(8);
        pdf.setTextColor(255, 255, 255);
        
        const footerText = branding.footerText || `Generated by ${branding.agencyName}`;
        pdf.text(
          `${footerText} - Page ${i} of ${pageCount}`,
          pdfWidth / 2,
          pdfHeight - 5,
          { align: 'center' }
        );
      } else {
        pdf.setFontSize(9);
        pdf.setTextColor(148, 163, 184);
        pdf.text(
          `Page ${i} of ${pageCount}`,
          pdfWidth / 2,
          pdfHeight - 10,
          { align: 'center' }
        );
      }
    }

    // Save PDF
    pdf.save(`${filename}.pdf`);
  } catch (error) {
    console.error('PDF export failed:', error);
    throw error;
  }
}

export function generateLeaseReviewReportPDF(
  reviews: any[], 
  stats: any, 
  demoData: any,
  branding?: PDFOptions['branding']
): jsPDF {
  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pdfHeight = pdf.internal.pageSize.getHeight();
  let yPos = 20;

  // Use brand colors or defaults
  const primaryColor = branding ? hexToPdfRgb(branding.colors.primary) : [37, 99, 235];
  const textColor = branding ? hexToPdfRgb(branding.colors.text) : [15, 23, 42];
  const mutedColor = branding ? hexToPdfRgb(branding.colors.textMuted) : [100, 116, 139];

  // Header with branding
  if (branding?.logoUrl) {
    addLogoToPDF(pdf, branding.logoUrl, 15, 10, 12);
    yPos = 15;
  }

  // Header
  pdf.setFontSize(24);
  pdf.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  pdf.text('Lease Review Report', pageWidth / 2, yPos, { align: 'center' });
  
  yPos += 10;
  pdf.setFontSize(12);
  pdf.setTextColor(mutedColor[0], mutedColor[1], mutedColor[2]);
  pdf.text(`Generated on ${new Date().toLocaleDateString()}`, pageWidth / 2, yPos, { align: 'center' });

  // Agency name
  if (branding) {
    yPos += 7;
    pdf.setFontSize(10);
    pdf.text(branding.agencyName, pageWidth / 2, yPos, { align: 'center' });
  }

  // Summary Stats
  yPos += 20;
  pdf.setFontSize(16);
  pdf.setTextColor(textColor[0], textColor[1], textColor[2]);
  pdf.text('Summary Statistics', 20, yPos);

  yPos += 10;
  pdf.setFontSize(11);
  pdf.setTextColor(mutedColor[0], mutedColor[1], mutedColor[2]);
  pdf.text(`Total Reviews: ${stats.total}`, 20, yPos);
  yPos += 7;
  pdf.text(`Completed: ${stats.completed}`, 20, yPos);
  yPos += 7;
  pdf.text(`Pending: ${stats.pending}`, 20, yPos);
  yPos += 7;
  pdf.text(`Flagged: ${stats.flagged}`, 20, yPos);
  yPos += 7;
  pdf.text(`Average On-Time Payment: ${stats.avgOnTimePayment}%`, 20, yPos);
  yPos += 7;
  pdf.text(`Recommend Renewal: ${stats.recommendRenewal}`, 20, yPos);

  // Reviews Table
  yPos += 20;
  pdf.setFontSize(16);
  pdf.setTextColor(textColor[0], textColor[1], textColor[2]);
  pdf.text('Lease Reviews', 20, yPos);

  // Table headers
  yPos += 10;
  pdf.setFillColor(248, 250, 252);
  pdf.rect(20, yPos - 5, pageWidth - 40, 10, 'F');
  pdf.setFontSize(9);
  pdf.setTextColor(mutedColor[0], mutedColor[1], mutedColor[2]);
  pdf.text('Tenant', 22, yPos);
  pdf.text('Property', 70, yPos);
  pdf.text('Rating', 120, yPos);
  pdf.text('Status', 145, yPos);
  pdf.text('Renewal', 170, yPos);

  // Table rows
  reviews.forEach((review, index) => {
    const tenant = demoData.tenants.find((t: any) => t.id === review.tenantId);
    const property = demoData.properties.find((p: any) => p.id === review.propertyId);
    
    yPos += 8;
    if (yPos > 270) {
      pdf.addPage();
      yPos = 20;
    }

    if (index % 2 === 0) {
      pdf.setFillColor(248, 250, 252);
      pdf.rect(20, yPos - 5, pageWidth - 40, 8, 'F');
    }

    pdf.setFontSize(8);
    pdf.setTextColor(textColor[0], textColor[1], textColor[2]);
    const tenantName = tenant ? `${tenant.firstName} ${tenant.lastName}` : 'Unknown';
    pdf.text(tenantName.substring(0, 20), 22, yPos);
    pdf.text((property?.title || 'Unknown').substring(0, 20), 70, yPos);
    pdf.text(review.complianceRating.charAt(0).toUpperCase() + review.complianceRating.slice(1), 120, yPos);
    pdf.text(review.status.charAt(0).toUpperCase() + review.status.slice(1), 145, yPos);
    pdf.text(review.recommendRenewal ? 'Yes' : 'No', 170, yPos);
  });

  // Footer
  const pageCount = pdf.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i);
    
    if (branding) {
      pdf.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
      pdf.rect(0, pdfHeight - 12, pageWidth, 12, 'F');
      pdf.setFontSize(8);
      pdf.setTextColor(255, 255, 255);
      const footerText = branding.footerText || `${branding.agencyName} - Lease Review Report`;
      pdf.text(`${footerText} - Page ${i} of ${pageCount}`, pageWidth / 2, pdfHeight - 5, { align: 'center' });
    } else {
      pdf.setFontSize(9);
      pdf.setTextColor(148, 163, 184);
      pdf.text(`Page ${i} of ${pageCount} - EazyRentals Lease Review Report`, pageWidth / 2, 285, { align: 'center' });
    }
  }

  return pdf;
}

export function generatePaymentReportPDF(
  payments: any[],
  stats: { totalPaid: number; totalOutstanding: number; totalPayments: number },
  demoData: any,
  branding?: PDFOptions['branding']
): jsPDF {
  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pdfHeight = pdf.internal.pageSize.getHeight();
  let yPos = 20;

  // Use brand colors or defaults
  const primaryColor = branding ? hexToPdfRgb(branding.colors.primary) : [37, 99, 235];
  const textColor = branding ? hexToPdfRgb(branding.colors.text) : [15, 23, 42];
  const mutedColor = branding ? hexToPdfRgb(branding.colors.textMuted) : [100, 116, 139];

  // Header with branding
  if (branding?.logoUrl) {
    addLogoToPDF(pdf, branding.logoUrl, 15, 10, 12);
    yPos = 15;
  }

  // Header
  pdf.setFontSize(24);
  pdf.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  pdf.text('Payment Report', pageWidth / 2, yPos, { align: 'center' });
  
  yPos += 10;
  pdf.setFontSize(12);
  pdf.setTextColor(mutedColor[0], mutedColor[1], mutedColor[2]);
  pdf.text(`Generated on ${new Date().toLocaleDateString()}`, pageWidth / 2, yPos, { align: 'center' });

  // Agency name
  if (branding) {
    yPos += 7;
    pdf.setFontSize(10);
    pdf.text(branding.agencyName, pageWidth / 2, yPos, { align: 'center' });
  }

  // Financial Summary
  yPos += 20;
  pdf.setFontSize(16);
  pdf.setTextColor(textColor[0], textColor[1], textColor[2]);
  pdf.text('Financial Summary', 20, yPos);

  yPos += 10;
  pdf.setFontSize(11);
  pdf.setTextColor(mutedColor[0], mutedColor[1], mutedColor[2]);
  pdf.text(`Total Payments: ${stats.totalPayments}`, 20, yPos);
  yPos += 7;
  pdf.text(`Total Collected: $${stats.totalPaid.toLocaleString()}`, 20, yPos);
  yPos += 7;
  pdf.text(`Outstanding: $${stats.totalOutstanding.toLocaleString()}`, 20, yPos);

  // Payments Table
  yPos += 20;
  pdf.setFontSize(16);
  pdf.setTextColor(textColor[0], textColor[1], textColor[2]);
  pdf.text('Payment Details', 20, yPos);

  // Table headers
  yPos += 10;
  pdf.setFillColor(248, 250, 252);
  pdf.rect(20, yPos - 5, pageWidth - 40, 10, 'F');
  pdf.setFontSize(9);
  pdf.setTextColor(mutedColor[0], mutedColor[1], mutedColor[2]);
  pdf.text('Tenant', 22, yPos);
  pdf.text('Amount', 70, yPos);
  pdf.text('Type', 100, yPos);
  pdf.text('Status', 130, yPos);
  pdf.text('Date', 160, yPos);

  // Table rows
  payments.forEach((payment, index) => {
    const tenant = demoData.tenants.find((t: any) => t.id === payment.tenantId);
    
    yPos += 8;
    if (yPos > 270) {
      pdf.addPage();
      yPos = 20;
    }

    if (index % 2 === 0) {
      pdf.setFillColor(248, 250, 252);
      pdf.rect(20, yPos - 5, pageWidth - 40, 8, 'F');
    }

    pdf.setFontSize(8);
    pdf.setTextColor(textColor[0], textColor[1], textColor[2]);
    const tenantName = tenant ? `${tenant.firstName} ${tenant.lastName}` : 'Unknown';
    pdf.text(tenantName.substring(0, 18), 22, yPos);
    pdf.text(`$${payment.amount.toLocaleString()}`, 70, yPos);
    pdf.text(payment.type.charAt(0).toUpperCase() + payment.type.slice(1), 100, yPos);
    pdf.text(payment.status.charAt(0).toUpperCase() + payment.status.slice(1), 130, yPos);
    pdf.text(payment.paidDate || payment.dueDate || '-', 160, yPos);
  });

  // Footer
  const pageCount = pdf.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i);
    
    if (branding) {
      pdf.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
      pdf.rect(0, pdfHeight - 12, pageWidth, 12, 'F');
      pdf.setFontSize(8);
      pdf.setTextColor(255, 255, 255);
      const footerText = branding.footerText || `${branding.agencyName} - Payment Report`;
      pdf.text(`${footerText} - Page ${i} of ${pageCount}`, pageWidth / 2, pdfHeight - 5, { align: 'center' });
    } else {
      pdf.setFontSize(9);
      pdf.setTextColor(148, 163, 184);
      pdf.text(`Page ${i} of ${pageCount} - EazyRentals Payment Report`, pageWidth / 2, 285, { align: 'center' });
    }
  }

  return pdf;
}

export function downloadPDF(pdf: jsPDF, filename: string): void {
  pdf.save(`${filename}-${new Date().toISOString().split('T')[0]}.pdf`);
}
